"""is superuser add field

Revision ID: 3415f737186b
Revises: 3aaab487c6d7
Create Date: 2024-07-07 21:13:39.232589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3415f737186b'
down_revision: Union[str, None] = '3aaab487c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'is_superuser')
    # ### end Alembic commands ###
